# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = 'ubuntu/trusty64'
# BOX = 'ubuntu/xenial64'
# BOX = 'geerlingguy/ubuntu1604'

# IP = '10.0.9.98'
IP = '192.196.2.98'
HOSTNAME = 'box.dev'
SERVER_CPUS = '1'      # Cores
SERVER_MEMORY = '1024' # MB
SERVER_SWAP = '2948'   # MB, between one or two times the SERVER_MEMORY
SERVER_TIMEZONE = 'EST'

RUBY = '2.3.0'
RUBY_GEMS = %q[bundler sass pry rubocop rails sinatra middleman jekyll ruby_parser rspec]
HOME = '/home/vagrant'

Vagrant.configure(2) do |config|
  config.vm.box = BOX

  # Setup networking in bridged mode
  config.vm.network "public_network", ip: IP

  # Setup synced folers
  # config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "../home", "/home/vagrant/",
    id: "home",
    create: true
    # :nfs => true,
    # :mount_options => ['nolock,vers=3,udp,noatime,actimeo=2,fsc']
  config.vm.synced_folder "../www", "/var/www",
    id: "www",
    create: true
    # group: "www-data",
    # owner: "www-data"

  # VirtualBox Specifics
  config.vm.provider "virtualbox" do |vb|
    vb.name = HOSTNAME
    vb.gui = false
    vb.cpus = SERVER_CPUS
    vb.memory = SERVER_MEMORY

    # Limit CPU execution to 50%
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]

    # Set the timesync threshold to 10 seconds, instead of the default 20 minutes
    # vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
  end

  config.vm.provision 'shell', path: './scripts/base.sh', args: [SERVER_SWAP, SERVER_TIMEZONE]
  config.vm.provision 'shell', path: './scripts/update.sh'
  config.vm.provision 'shell', path: './scripts/git.sh'
  config.vm.provision 'shell', path: './scripts/tmux.sh'
  config.vm.provision 'shell', path: './scripts/rbenv.sh', privileged: false
  config.vm.provision 'shell', path: './scripts/ruby.sh', args: [RUBY, RUBY_GEMS], privileged: false
  config.vm.provision 'shell', path: './scripts/dotfiles.sh', privileged: false
end
